surface.CreateFont("DarkRPFont", {font = "Roboto", size = 22})
surface.CreateFont("PlyCountFont", {font = "Roboto", size = 32, weight = 900})
surface.CreateFont("AliveFont", {font = "Roboto", size = 30, weight = 700})
surface.CreateFont("HealthFont", {font = "Roboto", size = 17})
surface.CreateFont("ClipFont", {font = "Roboto", size = 40})
surface.CreateFont("ExtraClipFont", {font = "Roboto", size = 27})
surface.CreateFont("DeathNoticeFont", {font = "Roboto", size = 19})
surface.CreateFont("OverheadNameFont", {font = "Roboto", size = 50, shadow = true})
surface.CreateFont("OverheadRPFont", {font = "Roboto", size = 40, shadow = true})
surface.CreateFont("OverheadHealthFont", {font = "Roboto", size = 33, shadow = true})